<?php

/**
 * @file
 * Primary module hooks for Tripticket Dashboard module.
 */

function tripticket_dashboard_theme($existing,$type,$theme,$path){


    $module_handler = \Drupal::serice('etension.list.module');
    $module_path = $module_handler->getPath('tripticket_dashboard');

    return[
            'tripticket_dashboard' => [
                            'template' => 'tripticket-dashboard',
                            'path' => $module_path . '/templates',

            ],


    ];

}
